import requests
import os
import time

class TextColors:
    BLACK = '\033[30m'
    RED  = '\033[31m'
    GREEN = '\033[32m'
    YELLOW = '\033[33m'
    BLUE  ='\033[34m'
    MAGENTA = '\033[35m'
    CYAN = '\033[36m'
    WHITE = '\033[37m'
    RESET = '\033[0m'
    LIGHT_MAGENTA = '\033[1;35m'

def userfinder_main():
    os.system('cls' if os.name == 'nt' else 'clear')
    print(TextColors.LIGHT_MAGENTA + """
  █    ██   ██████ ▓█████  ██▀███       █████▒██▓ ███▄    █ ▓█████▄ 
 ██  ▓██▒▒██    ▒ ▓█   ▀ ▓██ ▒ ██▒   ▓██   ▒▓██▒ ██ ▀█   █ ▒██▀ ██▌
▓██  ▒██░░ ▓██▄   ▒███   ▓██ ░▄█ ▒   ▒████ ░▒██▒▓██  ▀█ ██▒░██   █▌
▓▓█  ░██░  ▒   ██▒▒▓█  ▄ ▒██▀▀█▄     ░▓█▒  ░░██░▓██▒  ▐▌██▒░▓█▄   ▌
▒▒█████▓ ▒██████▒▒░▒████▒░██▓ ▒██▒   ░▒█░   ░██░▒██░   ▓██░░▒████▓ 
░▒▓▒ ▒ ▒ ▒ ▒▓▒ ▒ ░░░ ▒░ ░░ ▒▓ ░▒▓░    ▒ ░   ░▓  ░ ▒░   ▒ ▒  ▒▒▓  ▒ 
░░▒░ ░ ░ ░ ░▒  ░ ░ ░ ░  ░  ░▒ ░ ▒░    ░      ▒ ░░ ░░   ░ ▒░ ░ ▒  ▒ 
 ░░░ ░ ░ ░  ░  ░     ░     ░░   ░     ░ ░    ▒ ░   ░   ░ ░  ░ ░  ░ 
   ░           ░     ░  ░   ░                ░           ░    ░    
                                                            ░        
            """ + TextColors.RESET)

    user = input(TextColors.MAGENTA + "Username > " + TextColors.RESET)
    url_info(user)

def url_info(username):


# Total : 500

    urls = [
    ("Instagram", f"https://www.instagram.com/{username}/"),
    ("Facebook", f"https://www.facebook.com/{username}/"),
    ("YouTube", f"https://www.youtube.com/user/{username}"),
    ("Reddit", f"https://www.reddit.com/user/{username}/"),
    ("GitHub", f"https://github.com/{username}"),
    ("Twitch", f"https://www.twitch.tv/{username}"),
    ("Pinterest", f"https://www.pinterest.com/{username}/"),
    ("TikTok", f"https://www.tiktok.com/@{username}"),
    ("LinkedIn", f"https://www.linkedin.com/in/{username}/"),
    ("Snapchat", f"https://www.snapchat.com/add/{username}"),
    ("Tumblr", f"https://{username}.tumblr.com/"),
    ("Quora", f"https://www.quora.com/profile/{username}"),
    ("Medium", f"https://medium.com/@{username}"),
    ("SoundCloud", f"https://soundcloud.com/{username}"),
    ("Vimeo", f"https://vimeo.com/{username}"),
    ("Behance", f"https://www.behance.net/{username}"),
    ("Dribbble", f"https://dribbble.com/{username}"),
    ("Last.fm", f"https://last.fm/user/{username}"),
    ("MySpace", f"https://myspace.com/{username}"),
    ("Blogger", f"https://{username}.blogspot.com"),
    ("WordPress", f"https://{username}.wordpress.com/"),
    ("GitLab", f"https://gitlab.com/{username}"),
    ("Discord", f"https://discord.com/users/{username}"),
    ("Spotify", f"https://open.spotify.com/user/{username}"),
    ("Steam", f"https://steamcommunity.com/id/{username}"),
    ("Telegram", f"https://t.me/{username}"),
    ("Trello", f"https://trello.com/{username}"),
    ("Google Sites", f"https://sites.google.com/{username}"),
    ("Habitica", f"https://habitica.com/users/{username}"),
    ("Twitch Clips", f"https://www.twitch.tv/clips/user/{username}"),
    ("Minds", f"https://www.minds.com/{username}"),
    ("Bitly", f"https://bitly.com/{username}"),
    ("Origin", f"https://www.origin.com/profile/{username}"),
    ("Flickr", f"https://www.flickr.com/photos/{username}/"),
    ("MyAnimeList", f"https://myanimelist.net/profile/{username}"),
    ("DeviantArt", f"https://www.deviantart.com/{username}"),
    ("Cricbuzz", f"https://www.cricbuzz.com/profiles/{username}"),
    ("Meetup", f"https://www.meetup.com/members/{username}/"),
    ("Foursquare", f"https://foursquare.com/{username}"),
    ("Soundclick", f"https://www.soundclick.com/{username}"),
    ("Twitch Tracker", f"https://www.twitchtracker.com/{username}"),
    ("Yelp", f"https://www.yelp.com/user_details?userid={username}"),
    ("Couchsurfing", f"https://www.couchsurfing.com/people/{username}"),
    ("Vine", f"https://vine.co/u/{username}"),
    ("LiveJournal", f"https://{username}.livejournal.com/"),
    ("Steemit", f"https://steemit.com/@{username}"),
    ("Ello", f"https://ello.co/{username}"),
    ("Clash of Clans", f"https://clashofclans.com/en/players/{username}"),
    ("Wattpad", f"https://www.wattpad.com/user/{username}"),
    ("Quibblo", f"https://www.quibblo.com/user/{username}"),
    ("Goodreads", f"https://www.goodreads.com/user/show/{username}"),
    ("Yik Yak", f"https://www.yikyak.com/{username}"),
    ("Newgrounds", f"https://{username}.newgrounds.com/"),
    ("Ravelry", f"https://www.ravelry.com/people/{username}"),
    ("Scribophile", f"https://www.scribophile.com/profile/{username}"),
    ("Codecademy", f"https://www.codecademy.com/profiles/{username}"),
    ("Bandcamp", f"https://{username}.bandcamp.com/"),
    ("Coursera", f"https://www.coursera.org/user/{username}"),
    ("Udemy", f"https://www.udemy.com/user/{username}"),
    ("LinkedIn Learning", f"https://www.linkedin.com/learning/instructors/{username}"),
    ("Academic", f"https://academic.oup.com/{username}"),
    ("ResearchGate", f"https://www.researchgate.net/profile/{username}"),
    ("Kaggle", f"https://www.kaggle.com/{username}"),
    ("GitBook", f"https://{username}.gitbook.io/"),
    ("Baidu", f"https://tieba.baidu.com/home/main?id={username}"),
    ("Wikidot", f"https://{username}.wikidot.com/"),
    ("Tableau", f"https://public.tableau.com/profile/{username}"),
    ("Fiverr", f"https://www.fiverr.com/{username}"),
    ("99designs", f"https://99designs.com/profiles/{username}"),
    ("Envato", f"https://envato.com/user/{username}/"),
    ("GitHub Gists", f"https://gist.github.com/{username}"),
    ("Twitch Dashboard", f"https://dashboard.twitch.tv/u/{username}/"),
    ("Raspberry Pi", f"https://www.raspberrypi.org/users/{username}/"),
    ("Notion", f"https://www.notion.so/{username}"),
    ("Zoho", f"https://www.zoho.com/{username}"),
    ("Glitch", f"https://glitch.com/@{username}"),
    ("Bitbucket", f"https://bitbucket.org/{username}"),
    ("DuckDuckGo", f"https://duckduckgo.com/?q={username}"),
    ("Pixiv", f"https://www.pixiv.net/en/users/{username}"),
    ("Dailymotion", f"https://www.dailymotion.com/user/{username}"),
    ("Live.com", f"https://login.live.com/login.srf?id={username}"),
    ("Cricinfo", f"https://www.espncricinfo.com/player/{username}"),
    ("Fandango", f"https://www.fandango.com/{username}"),
    ("SBCGlobal", f"https://sbcglobal.net/mail/{username}"),
    ("ProtonMail", f"https://protonmail.com/{username}"),
    ("Mail.com", f"https://www.mail.com/mail/{username}"),
    ("AOL", f"https://login.aol.com/account/security/{username}"),
    ("Yahoo", f"https://login.yahoo.com/?.src=ym&.intl=us&login={username}"),
    ("FastMail", f"https://www.fastmail.com/?username={username}"),
    ("Zoho Mail", f"https://www.zoho.com/mail/m/{username}"),
    ("GMX", f"https://www.gmx.com/mail/{username}"),
    ("Tutanota", f"https://tutanota.com/{username}"),
    ("Hushmail", f"https://www.hushmail.com/{username}"),
    ("Mail.ru", f"https://mail.ru/{username}"),
    ("iCloud", f"https://www.icloud.com/{username}"),
    ("Yandex Mail", f"https://mail.yandex.com/{username}"),
    ("Kik", f"https://kik.com/{username}"),
    ("MeetMe", f"https://www.meetme.com/{username}"),
    ("Badoo", f"https://badoo.com/en/{username}/"),
    ("OkCupid", f"https://www.okcupid.com/profile/{username}"),
    ("Tinder", f"https://tinder.com/@{username}"),
    ("Plenty of Fish", f"https://www.pof.com/viewprofile.aspx?userid={username}"),
    ("Match.com", f"https://www.match.com/profile/{username}"),
    ("Hinge", f"https://hinge.co/{username}"),
    ("Skout", f"https://www.skout.com/{username}"),
    ("Twoo", f"https://www.twoo.com/{username}"),
    ("Whisper", f"https://whisper.sh/@{username}"),
    ("Grindr", f"https://grindr.com/{username}"),
    ("BlackPeopleMeet", f"https://www.blackpeoplemeet.com/{username}"),
    ("JSwipe", f"https://jswipe.com/profile/{username}"),
    ("Chappy", f"https://www.chappyapp.com/{username}"),
    ("eHarmony", f"https://www.eharmony.com/profile/{username}"),
    ("EliteSingles", f"https://www.elitesingles.com/profile/{username}"),
    ("Fling", f"https://www.fling.com/profile/{username}"),
    ("AdultFriendFinder", f"https://www.adultfriendfinder.com/{username}"),
    ("XDating", f"https://xdating.com/{username}"),
    ("Happn", f"https://www.happn.com/profile/{username}"),
    ("Smooch", f"https://www.smooch.com/{username}"),
    ("Sizzle", f"https://sizzle.com/{username}"),
    ("FetLife", f"https://fetlife.com/{username}"),
    ("Bumble", f"https://bumble.com/{username}"),
    ("Coffee Meets Bagel", f"https://coffeemeetsbagel.com/{username}"),
    ("Jdate", f"https://www.jdate.com/profile/{username}"),
    ("CatholicMatch", f"https://www.catholicmatch.com/{username}"),
    ("DateMySchool", f"https://datemyschool.com/profile/{username}"),
    ("SingleParentMeet", f"https://www.singleparentmeet.com/{username}"),
    ("OurTime", f"https://www.ourtime.com/profile/{username}"),
    ("SeniorMatch", f"https://www.seniormatch.com/profile/{username}"),
    ("SilverSingles", f"https://www.silversingles.com/profile/{username}"),
    ("Tastebuds", f"https://tastebuds.fm/profile/{username}"),
    ("GetCoffee", f"https://getcoffee.com/{username}"),
    ("Tandem", f"https://www.tandem.net/{username}"),
    ("Meetup", f"https://www.meetup.com/members/{username}/"),
    ("Eventbrite", f"https://www.eventbrite.com/d/online/all-events/?q={username}"),
    ("Facebook Events", f"https://www.facebook.com/events/search/?q={username}"),
    ("MeetMe", f"https://www.meetme.com/{username}"),
    ("Tumblr", f"https://{username}.tumblr.com/"),
    ("Mastodon", f"https://mastodon.social/@{username}"),
    ("Ello", f"https://ello.co/{username}"),
    ("Goodreads", f"https://www.goodreads.com/user/show/{username}"),
    ("Wattpad", f"https://www.wattpad.com/user/{username}"),
    ("BookCrossing", f"https://www.bookcrossing.com/member/{username}"),
    ("LibraryThing", f"https://www.librarything.com/profile/{username}"),
    ("Shelfari", f"https://www.shelfari.com/{username}"),
    ("Google Books", f"https://books.google.com/books?uid={username}"),
    ("Open Library", f"https://openlibrary.org/users/{username}"),
    ("GoodReads", f"https://www.goodreads.com/user/show/{username}"),
    ("BookBub", f"https://www.bookbub.com/profile/{username}"),
    ("Litsy", f"https://litsy.com/{username}"),
    ("RiffTrax", f"https://www.rifftrax.com/user/{username}"),
    ("Fandom", f"https://fandom.com/u/{username}"),
    ("StumbleUpon", f"https://www.stumbleupon.com/user/{username}"),
    ("Delicious", f"https://del.icio.us/{username}"),
    ("Digg", f"https://digg.com/u/{username}"),
    ("Quora", f"https://www.quora.com/profile/{username}"),
    ("Fark", f"https://www.fark.com/user/{username}"),
    ("Slashdot", f"https://slashdot.org/user/{username}"),
    ("DZone", f"https://dzone.com/users/{username}"),
    ("Hacker News", f"https://news.ycombinator.com/user?id{username}"),
    ("Product Hunt", f"https://www.producthunt.com/@{username}"),
    ("Dev.to", f"https://dev.to/{username}"),
    ("GitHub", f"https://github.com/{username}"),
    ("CodePen", f"https://codepen.io/{username}"),
    ("Repl.it", f"https://replit.com/@{username}"),
    ("Stack Overflow", f"https://stackoverflow.com/users/{username}"),
    ("FreeCodeCamp", f"https://www.freecodecamp.org/{username}"),
    ("Coursera", f"https://www.coursera.org/user/{username}"),
    ("Udacity", f"https://www.udacity.com/user/{username}"),
    ("Khan Academy", f"https://www.khanacademy.org/user/{username}"),
    ("Skillshare", f"https://www.skillshare.com/user/{username}"),
    ("LinkedIn Learning", f"https://www.linkedin.com/learning/instructors/{username}"),
    ("Pluralsight", f"https://www.pluralsight.com/profile/{username}"),
    ("Codecademy", f"https://www.codecademy.com/profiles/{username}"),
    ("edX", f"https://www.edx.org/user/{username}"),
    ("Treehouse", f"https://teamtreehouse.com/{username}"),
    ("GitLab", f"https://gitlab.com/{username}"),
    ("Bitbucket", f"https://bitbucket.org/{username}"),
    ("SourceForge", f"https://sourceforge.net/users/{username}"),
    ("Launchpad", f"https://launchpad.net/~{username}"),
    ("GitKraken", f"https://www.gitkraken.com/u/{username}"),
    ("Bitrise", f"https://www.bitrise.io/{username}"),
    ("Heroku", f"https://dashboard.heroku.com/apps/{username}"),
    ("Firebase", f"https://console.firebase.google.com/u/0/project/{username}/overview"),
    ("DigitalOcean", f"https://cloud.digitalocean.com/teams/{username}/"),
    ("Linode", f"https://manager.linode.com/users/{username}"),
    ("Vultr", f"https://my.vultr.com/accounts/{username}/"),
    ("Amazon Web Services", f"https://aws.amazon.com/console/?actionlogin&username{username}"),
    ("Google Cloud Platform", f"https://console.cloud.google.com/home/dashboard?authuser{username}"),
    ("Microsoft Azure", f"https://portal.azure.com/?username{username}"),
    ("IBM Cloud", f"https://cloud.ibm.com/login?username{username}"),
    ("Salesforce", f"https://login.salesforce.com/?username{username}"),
    ("Zoho", f"https://www.zoho.com/login/{username}"),
    ("HubSpot", f"https://app.hubspot.com/login/{username}"),
    ("Intercom", f"https://app.intercom.com/login/{username}"),
    ("Mailchimp", f"https://login.mailchimp.com/?username{username}"),
    ("Trello", f"https://trello.com/{username}"),
    ("Slack", f"https://slack.com/signin/{username}"),
    ("Asana", f"https://app.asana.com/-/{username}/"),
    ("Monday.com", f"https://monday.com/login/{username}"),
    ("Jira", f"https://jira.atlassian.com/login?username{username}"),
    ("ClickUp", f"https://app.clickup.com/login/{username}"),
    ("Todoist", f"https://todoist.com/users/{username}/"),
    ("Notion", f"https://www.notion.so/{username}"),
    ("Evernote", f"https://www.evernote.com/Login.action?username{username}"),
    ("Microsoft OneNote", f"https://www.onenote.com/login?username{username}"),
    ("Google Keep", f"https://keep.google.com/u/0/#note/{username}"),
    ("Miro", f"https://miro.com/login?username{username}"),
    ("Lucidchart", f"https://www.lucidchart.com/user/login/{username}"),
    ("Visme", f"https://www.visme.co/login/{username}"),
    ("Trello", f"https://trello.com/{username}"),
    ("Basecamp", f"https://basecamp.com/login/{username}"),
    ("Airtable", f"https://airtable.com/login/{username}"),
    ("Notion", f"https://www.notion.so/{username}"),
    ("ClickUp", f"https://app.clickup.com/login/{username}"),
    ("Teamwork", f"https://www.teamwork.com/login/{username}"),
    ("Wrike", f"https://www.wrike.com/login/{username}"),
    ("Smartsheet", f"https://www.smartsheet.com/login/{username}"),
    ("Podio", f"https://podio.com/login/{username}"),
    ("Figma", f"https://www.figma.com/login/{username}"),
    ("Sketch", f"https://www.sketch.com/login/{username}"),
    ("Adobe XD", f"https://www.adobe.com/go/xd/login/{username}"),
    ("InVision", f"https://www.invisionapp.com/login/{username}"),
    ("Canva", f"https://www.canva.com/login/{username}"),
    ("Visme", f"https://www.visme.co/login/{username}"),
    ("Pixlr", f"https://pixlr.com/login/{username}"),
    ("Photopea", f"https://www.photopea.com/login/{username}"),
    ("PicMonkey", f"https://www.picmonkey.com/login/{username}"),
    ("Crello", f"https://crello.com/login/{username}"),
    ("Visme", f"https://www.visme.co/login/{username}"),
    ("Blogger", f"https://{username}.blogspot.com"),
    ("Medium", f"https://medium.com/@{username}"),
    ("Substack", f"https://substack.com/{username}"),
    ("WordPress", f"https://{username}.wordpress.com/"),
    ("Ghost", f"https://ghost.org/{username}/"),
    ("Wix", f"https://www.wix.com/dashboard/{username}"),
    ("Squarespace", f"https://www.squarespace.com/login/{username}"),
    ("Weebly", f"https://www.weebly.com/login/{username}"),
    ("Site123", f"https://www.site123.com/login/{username}"),
    ("Webnode", f"https://www.webnode.com/login/{username}"),
    ("Webflow", f"https://webflow.com/login/{username}"),
    ("Jimdo", f"https://www.jimdo.com/login/{username}"),
    ("Blogger", f"https://{username}.blogspot.com"),
    ("Google Sites", f"https://sites.google.com/{username}"),
    ("Yola", f"https://www.yola.com/login/{username}"),
    ("WordPress.com", f"https://wordpress.com/log-in/{username}"),
    ("Zoho Sites", f"https://www.zoho.com/sites/login/{username}"),
    ("Webstarts", f"https://www.webstarts.com/login/{username}"),
    ("Ucraft", f"https://www.ucraft.com/login/{username}"),
    ("Strikingly", f"https://www.strikingly.com/login/{username}"),
    ("Duda", f"https://www.duda.com/login/{username}"),
    ("Squarespace", f"https://www.squarespace.com/login/{username}"),
    ("SiteBuilder", f"https://sitebuilder.com/login/{username}"),
    ("Gatsby", f"https://www.gatsbyjs.com/login/{username}"),
    ("Hugo", f"https://gohugo.io/login/{username}"),
    ("Joomla", f"https://www.joomla.org/login/{username}"),
    ("Drupal", f"https://www.drupal.org/login/{username}"),
    ("Magento", f"https://magento.com/login/{username}"),
    ("Shopify", f"https://www.shopify.com/login/{username}"),
    ("BigCommerce", f"https://www.bigcommerce.com/login/{username}"),
    ("WooCommerce", f"https://woocommerce.com/login/{username}"),
    ("PrestaShop", f"https://www.prestashop.com/login/{username}"),
    ("OpenCart", f"https://www.opencart.com/login/{username}"),
    ("Zen Cart", f"https://www.zen-cart.com/login/{username}"),
    ("osCommerce", f"https://www.oscommerce.com/login/{username}"),
    ("3dcart", f"https://www.3dcart.com/login/{username}"),
    ("Volusion", f"https://www.volusion.com/login/{username}"),
    ("Square", f"https://squareup.com/login/{username}"),
    ("Weebly", f"https://www.weebly.com/login/{username}"),
    ("Fiverr", f"https://www.fiverr.com/{username}"),
    ("Upwork", f"https://www.upwork.com/freelancers/~{username}"),
    ("Freelancer", f"https://www.freelancer.com/u/{username}"),
    ("PeoplePerHour", f"https://www.peopleperhour.com/freelancer/{username}"),
    ("Guru", f"https://www.guru.com/freelancers/{username}"),
    ("99designs", f"https://99designs.com/profiles/{username}"),
    ("Toptal", f"https://www.toptal.com/resume/{username}"),
    ("DesignCrowd", f"https://www.designcrowd.com/profile/{username}"),
    ("SimplyHired", f"https://www.simplyhired.com/user/{username}"),
    ("Glassdoor", f"https://www.glassdoor.com/Profile/{username}"),
    ("Monster", f"https://www.monster.com/profiles/{username}"),
    ("LinkedIn", f"https://www.linkedin.com/in/{username}/"),
    ("ZipRecruiter", f"https://www.ziprecruiter.com/user/{username}"),
    ("CareerBuilder", f"https://www.careerbuilder.com/profile/{username}"),
    ("Jobcase", f"https://www.jobcase.com/user/{username}"),
    ("Snagajob", f"https://www.snagajob.com/profile/{username}"),
    ("SimplyHired", f"https://www.simplyhired.com/user/{username}"),
    ("Recruitment", f"https://www.recruitment.com/user/{username}"),
    ("Workable", f"https://www.workable.com/user/{username}"),
    ("BambooHR", f"https://www.bamboohr.com/user/{username}"),
    ("Zoho Recruit", f"https://www.zoho.com/recruit/login/{username}"),
    ("Bullhorn", f"https://www.bullhorn.com/user/{username}"),
    ("HRCloud", f"https://www.hrcloud.com/user/{username}"),
    ("iCIMS", f"https://www.icims.com/user/{username}"),
    ("SmartRecruiters", f"https://www.smartrecruiters.com/user/{username}"),
    ("Hireology", f"https://www.hireology.com/user/{username}"),
    ("BambooHR", f"https://www.bamboohr.com/user/{username}"),
    ("Workable", f"https://www.workable.com/user/{username}"),
    ("Greenhouse", f"https://www.greenhouse.io/user/{username}"),
    ("Jobvite", f"https://www.jobvite.com/user/{username}"),
    ("Lever", f"https://www.lever.co/user/{username}"),
    ("JazzHR", f"https://www.jazzhr.com/user/{username}"),
    ("ApplicantPro", f"https://www.applicantpro.com/user/{username}"),
    ("ClearCompany", f"https://www.clearcompany.com/user/{username}"),
    ("Breezy HR", f"https://breezy.hr/user/{username}"),
    ("Jobsoid", f"https://jobsoid.com/user/{username}"),
    ("Recruiterbox", f"https://recruiterbox.com/user/{username}"),
    ("TalentLyft", f"https://www.talentlyft.com/user/{username}"),
    ("SmartRecruiters", f"https://www.smartrecruiters.com/user/{username}"),
    ("HireHive", f"https://www.hirehive.com/user/{username}"),
    ("BambooHR", f"https://www.bamboohr.com/user/{username}"),
    ("Workable", f"https://www.workable.com/user/{username}"),
    ("Greenhouse", f"https://www.greenhouse.io/user/{username}"),
    ("Jobvite", f"https://www.jobvite.com/user/{username}"),
    ("Lever", f"https://www.lever.co/user/{username}"),
    ("JazzHR", f"https://www.jazzhr.com/user/{username}"),
    ("ApplicantPro", f"https://www.applicantpro.com/user/{username}"),
    ("ClearCompany", f"https://www.clearcompany.com/user/{username}"),
    ("Breezy HR", f"https://breezy.hr/user/{username}"),
    ("Jobsoid", f"https://jobsoid.com/user/{username}"),
    ("Recruiterbox", f"https://recruiterbox.com/user/{username}"),
    ("TalentLyft", f"https://www.talentlyft.com/user/{username}"),
    ("SmartRecruiters", f"https://www.smartrecruiters.com/user/{username}"),
    ("HireHive", f"https://www.hirehive.com/user/{username}"),
    ("BambooHR", f"https://www.bamboohr.com/user/{username}"),
    ("Workable", f"https://www.workable.com/user/{username}"),
    ("Greenhouse", f"https://www.greenhouse.io/user/{username}"),
    ("Jobvite", f"https://www.jobvite.com/user/{username}"),
    ("Lever", f"https://www.lever.co/user/{username}"),
    ("JazzHR", f"https://www.jazzhr.com/user/{username}"),
    ("ApplicantPro", f"https://www.applicantpro.com/user/{username}"),
    ("ClearCompany", f"https://www.clearcompany.com/user/{username}"),
    ("Breezy HR", f"https://breezy.hr/user/{username}"),
    ("Jobsoid", f"https://jobsoid.com/user/{username}"),
    ("Recruiterbox", f"https://recruiterbox.com/user/{username}"),
    ("TalentLyft", f"https://www.talentlyft.com/user/{username}"),
    ("SmartRecruiters", f"https://www.smartrecruiters.com/user/{username}"),
    ("HireHive", f"https://www.hirehive.com/user/{username}"),
]

    for platform, url in urls:
        try:
            response  = requests.get(url, timeout=5)
            response.raise_for_status()
            print(TextColors.CYAN + f"[+] {platform}:  Found! {url}" + TextColors.RESET)
        except requests.exceptions.HTTPError as http_err:
            print(TextColors.RED + f"[-] {platform}:   Not Found! {url}" + TextColors.RESET)
        except requests.exceptions.ConnectionError as conn_err:
            print(TextColors.RED + f"[-] {platform}:   Not Found! {url}" + TextColors.RESET)
        except requests.exceptions.Timeout:
            print(TextColors.RED + f"[-] {platform}:   Not Found! {url}" + TextColors.RESET)
        except requests.exceptions.RequestException as req_err:
            print(TextColors.RED + f"[-] {platform}:   Not Found! {url}" + TextColors.RESET)
            

if __name__ == "__main__":
    userfinder_main()







